### ISSUE TITLE
Implement automatic id generation for topics

### ISSUE THREAD

**Issue by matthew-william-lock** [matthew-william-lock/smarc_nm3_coms#2]
The given ```config.yaml``` assigns unique ids to topics. Since topics are duplicated for all nodes, the ids do not end up being unique. 

```
modem_address: 111
modem_name: sam
nodes:
  - base_station: 123
  - test_station: 123
topics:
  - topic:
      topic_name: navigation_report
      ros_msg_type: ros_dccl_msg_converter/NavigationReport
      dccl_msg_type: NavigationReport
      topic_id: 1
  - topic:
      topic_name: navigation_report_two
      ros_msg_type: ros_dccl_msg_converter/NavigationReport
      dccl_msg_type: NavigationReport
      topic_id: 2
```

Possible solutions:
- Make topic declaration more flexible on a per-node basis
- remove ```topic_id``` from the ```config.yaml``` and make it automatic when parsing the config
